dist: focal
language: node_js
cache: yarn
node_js:
  - '10'
  - '14'
env:
  - CREATE_PROJECT_YARN=true
  - CREATE_PROJECT_YARN=false
jobs:
  include:
    - if: type != pull_request AND branch = master
      node_js: '12'
before_install:
  # Use newer yarn than that pre-installed in the Travis image.
  - curl -sSfL https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --frozen-lockfile
script:
  - yarn validate:eslintrc
  - yarn lint
  - yarn prettier:check
  - yarn test
  - scripts/test-create-project-ci.sh
