[build]
  # Using a non-root base directory/requirements file to prevent
  # Netlify from finding package.json and trying to install that:
  # https://github.com/netlify/build-image/issues/141
  base    = "docs"
  publish = "build"
  command = "../scripts/build-docs.sh"

# Redirect domain aliases to the primary domain.

[[redirects]]
  from = "https://neutrino.js.org/*"
  to = "https://neutrinojs.org/:splat"
  force = true

[[redirects]]
  from = "https://neutrinojs.netlify.com/*"
  to = "https://neutrinojs.org/:splat"
  force = true
